inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
Naming/MethodParameterName:
  MinNameLength: 2
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/FileName:
  Exclude: [lib/sortable-by.rb]
Metrics/ParameterLists:
  Max: 10
